---
title: "Academic Writing Sample"
format: html
editor: visual
---

Below is the text of a final research paper I wrote for my International Organizations course at George Washington University. For my research topic, I decided to delve into the inter-related issues of illicit arms trafficking and gun violence. After a brief overview of the topic, I go into the causes of these issues, and key actors including governments, buyers and sellers. After that, I describe agendas and initiatives of international organizations such as the United Nations, European Union, the Organization of American States, and the Organization of African Unity. I conclude with potential solutions such as International Firearm Microstamping (IFM) technology.

# International Organizations Final Research Paper: Illicit Arms Trafficking and Gun Violence

The illicit trade of small arms and subsequent gun violence is a prominent issue globally, occurring both as a consequence and cause of social, economic and political issues. The gravity of this problem lies in the inherent violation of the human right to life due to the accessibility of guns through illegal markets, given that gun-related injuries account for more than 500 deaths, and 2,000 injuries on a daily basis (Amnesty International, 2021). Although anyone can be impacted by illicit arms trafficking, the groups most significantly affected by the global presence of these guns consist of communities of color, young men, female victims of abuse, and other members of marginalized societal groups (Amnesty International, 2021). Additionally, while  44% of documented homicides across the world involve gun violence, there is a condensation of especially high rates in Latin American countries, such as El Salvador, Brazil, and Honduras (Amnesty International, 2021). 

The cause of this issue lies in easy access to firearms through illicit markets, especially those on the \'darknet\' (Amnesty International, 2021). Even legal gun distributors, such as Guns International, specifically advertise the accessibility of their products as a hallmark trait of their services (GunsInternational.com, 2021), further cementing this notion as an industry-wide expectation. Additionally, the draw of easy profits drives illegal straw purchase sales of otherwise legal firearms, wherein someone who would not otherwise be able to obtains a firearm through another person who can legally do so (Noyes, 2014). These practices of distribution enable easy access to guns globally, as exhibited through the expanse of illicit small arms trafficking. According to the 2020 Global Study on Firearms published by the UN, over 550,000 illicit firearms were seized globally throughout 2016 and 2017 (United Nations, 2020). In the presence of interstate collaborative efforts in combating the illicit trafficking of small arms, gun violence and the subsequent violations of human rights would not be possible in the first place. 

The key actors involved in the issue of illegal access to guns include the producers and distributors, owners, governments, and the humanitarian IOs fighting against the illicit firearm industry and the human rights violations entangled within it. The goals of the individuals and corporate entities within the illicit firearm industry revolve around making a profit and running a successful business, while evading prosecution. This is emphasized by the sheer worth of this industry, given that 8 million small guns and as many as 15 billion rounds of ammunition are produced each year, making the legal small arms trade alone worth approximately \$8.5 billion annually (Amnesty International, 2021), and although the nature of the illicit industry is inherently illusive, it is also estimated to be worth billions of dollars (United Nations, 2020). The value of this industry intensifies the desire of these actors responsible for the presence of illegal guns in maintaining their roles in production and distribution. The value of this industry also serves to draw individuals into this illicit trade, further increasing the expanse of this network.

The consumers within this illicit market are generally motivated either by the draw of power or of self-protection. Those who consume firearms from those trafficking them for the sake of power primarily consist of organized crime and terrorist organizations, who utilize violence and fear to assert control (United Nations, 2020). The presence of these guns held by threatening entities often incentivizes everyday citizens to acquire small arms for their own self-protection. However, guns yield a false sense of safety, being that the presence of guns can make crimes more violent than they otherwise would be (Harvard, 2016). This exhibits how gun ownership can decrease the general feelings of safety within a community, inspiring more gun ownership and beginning the snowball effect that is gun violence.

Governments are also main actors in regard to this problem, as they hold the power to implement regulations and fund efforts to dismantle the international network of small arms trafficking. The motives behind the varying governmental involvements in solving this issue are mainly consequences of their individual economic or political motives. These economic motives can include governmental entanglement with the illicit small arms industry, and subsequent support for the continued illegal distribution of small arms (Greene, 2000). Additionally, the political notion of gun rights being equivalent to human rights has also had great influence on governmental actions, especially within partisan political environments, wherein one's success in a political party can be determined in part by their views on this issue. Regardless of governmental stance in regard to this issue, a key contributor to the supply of illicit small arms is a result of the failure of governments to secure their existing stockpiles (Lizotte & Ohar, 2009).

Within the world of International Organizations, the illicit trafficking of small arms has been present on the agenda since 1996 (Greene, 2000). The United Nations is a prominent actor within the international issue of illegal access to guns. This IO is representative of the humanitarian motivations behind efforts towards solving the problem of the illicit small arms trade. The actions taken by this international organization to achieve this goal include the Program of Action to Prevent, Combat and Eradicate the Illicit Trade in Small Arms and Light Weapons in All Its Aspects (PoA) adopted in 2001, through which governments agreed to adequately mark and track firearms in their possession and to cooperate with other governments in these efforts (United Nations, 2021). Another effort made by the UN in tackling the illicit arms trade was the implementation of the International Tracing Instrument (ITI) in 2005, which was intended to be a universal means of weapons tracing (United Nations, 2021). However, agreement without accountability is insufficient, as there is no way for an IO to single-handedly hold states accountable for these requests. Therefore, although these would be productive solutions, they have been largely unsuccessful due to the reliance of humanitarian IOs on government cooperation to execute their goals. 

Numerous other efforts have been made in combating the illegal access to small arms, as since 1997 initiatives have been taken by many IOs such as the European Union, the Organization of American States, and the Organization of African Unity (Greene, 2000). Initiatives taken by these IOs generally consisted of attempts to deplete stockpiles of small arms and prosecute those responsible for trafficking. Unfortunately, such initiatives and resolutions have had little effect, considering that this issue remains unresolved and a frequent topic within the UN (Security Council, 2021). The failure of these efforts lies in the fact that many governments are active in the trade of illicit arms, both through facilitation and intentional ignorance, and are therefore incentivized to limit the effectiveness of these solutions (Greene 2000). Additionally, those governments who are not actively involved in the industry still often lack the capacity to single-handedly combat an international illicit industry, and efforts of IOs have lacked adequate means of enabling and reinforcing necessary governmental action (Greene, 2000).

Failures in attempting to diminish the threat of gun violence are also due to the difficulty in marking and tracking firearms in order to effectively identify and prevent illegal acquisition. Just with all regulated or illegal commodities, if people want guns, they will find a way to get them, and thus the only viable solution is to effectively track and trace these weapons to their source and cut supply from there. Although the UN has the ITI system in place, it has not been successful in standardizing this marking method across states, and thus this system is rendered ineffective in tracking global movements of illicit small arms (Lizotte & Ohar, 2009). Even if this system was successfully standardized, advancements remain critical as this technology is limited to firearms found at crime scenes, as opposed to both the firearm and cartridge ejected by the firearm (Lizotte & Ohar, 2009). Given that most firearms are not recovered at crime scenes, these markers are often rendered useless in their purpose (Lizotte & Ohar, 2009). The ITI system exhibits the desire within the UN to combat this issue, along with the advancements required to do so successfully.

What is necessary in effectively combating illicit small arms trafficking is interstate cooperation in both the implementations of technological advancements and measures to destroy the supply of illicit small arms. Despite past attempts, there is a continued need for these developments on behalf of the UN if it is to adequately fulfill its role as an international peacekeeping organization, considering the continued rate of violence and death enabled by this illicit small arms trade. If it is to enable sufficient means of tracking the illicit trade of small arms, the UN must replace the ITI and update the system as a whole to include adequate technology, while incentivizing member states to implement through means of funding and negotiation with hesitant states. This would enable efficient and accurate tracking of the illicit arms trade globally. The UN can achieve this by implementing the Intentional Firearm Microstamping (IFM) technology, which includes means of identifying cartridges found on the scene (Lizotte & Ohar, 2009). To effectively implement this technology, the UN Office for Disarmament Affairs (UNODA) must shift its Programme of Action / ITI (UNODA) to include or replace ITI with IFM technologies. This is among the most viable solutions in combating the international illicit arms trade, given that it eliminates the difficulties in tracking the flow of this trade posed by inconsistent and ineffective means of tracking small arms. 

Another solution to this issue that must be taken on behalf of the UN is facilitating the governmental collection and destruction of small arms stockpiles (Green 2006). This is necessary in solving the problem of the illicit small arms trade, given that without a supply of small arms this network would cease to exist. The collection and destruction of stockpiled small arms has already been proven to be successful in reducing the supply of small arms at risk of being illicitly trafficked. This is exhibited by the collaborative effort between the United States and the OAS, in which the U.S. provided \$50,000 in support of the destruction of these small arms stockpiles in Central America (Green, 2006). This funding enabled the destruction of 100 tons of small arms in Nicaragua alone (Green, 2006). It is clear that if the UN were to implement a version of this process on a global scale, the supply of arms at risk of being trafficked would decrease significantly. The most viable means of this implementation would be by tasking the UN Group of Governmental Experts on Surplus Ammunition to actively assist states in their stockpile destruction through both funding and strategies (Peters, 2021).

The implementation of the IMF technology and a program for the destruction of arms stockpiles will require funding and manpower, all to be approved and voted into action by the UN General Assembly (UN, 2021). The necessary funding can be estimated at about \$50,000 per region (to be reassessed annually) that intends to destroy its stockpiles, based upon the amount provided by the U.S. to Central America. Meanwhile, the required manpower can be sourced from current members and individuals who already support and ensured the installation of ITI technology to simply switch focus to IMF technology, as a reallocation of existing resources. The UN has the technical capacity to effectively implement these reforms, as exhibited by its previous ability to attain support for and implement similar initiatives. These similar initiatives include the PoA and the implementation of ITI technology. Although these past actions have proven to be inadequate, the passage and attempted implementation alone shows the desire and technical capacity within the UN to do so successfully when using effective strategies such as directly funding the implementation of IFM technology in addition to governmental stockpile destruction programs. The UN also continues to maintain the financial ability to reform these past efforts, given that the organization receives approximately \$8 billion annually from the U.S. alone (May 2017) and\$245,780,747 was provided directly from the Russian Federation, Niger, and Germany, all of which have been adamant in their will to combat the illicit gun trade (UN Committee on Contributions, 2021). In addition, although the UN does not have the immediate capacity to hold member states accountable to these reforms, successful implementation of IFM technology among even half of the UN\'s members could aid significantly in identifying governments guilty of contributing to this issue and enable accountability.

Additionally, these institutional reforms are politically viable given the desire to implement such changes among powerful member states such as the U.S. This is exemplified through the U.S.\'s hope that the \$50,000 it provided to the OAS for small arms destruction will inspire other wealthy nations to act similarly (Green, 2006). The 2030 Agenda for Sustainable Development also includes improving weapons tracing, an action which all member states have agreed upon (United Nations 2021). There have also been explicit requests for the implementation of these reforms within the UN, as during a recent Security Council meeting, members called for early adoption of measures to address the growing role of the darknet in the illicit trafficking of small arms, which include reformed means of tracking (Security Council, 2021). 

Despite this previous support for similar initiatives within the UN and member states, there is also expected to be pushback on behalf of gun rights advocates and gun owners, particularly against the IMF arms tracking technologies. These views can influence the actions of a member state within the UN. However, some of the post prominent pro-gun states such as the U.S. have already funded actions against accessibility to illicit small arms (Green, 2006). Furthermore, other member states have exhibited their recognition and desire for enhancing the UN\'s capacity to limit the illicit arms trade, as at a Security Council meeting earlier this year many members of the council agreed that the proliferation of small arms and the illicit trade remains a prominent issues, and some spoke directly of the technologies combating illicit trade such as the ITI (UN Security Council, 2021). Specifically, Germany, Niger, and the Russian Federation called for improvements in the UN\'s infrastructure surrounding the revention of the trade of illicit arms (UN Security Council, 2021). These nations each have their own advocates for gun rights, and yet they continue to advocate for further control over the illicit trade on behalf of the UN, exhibiting the political capacity of these solutions. Additionally, any gun manufacturer that advocates against the tracking and destruction of illicit weapons risks self-incrimination for entanglement within the illicit arms trade.

As the body count continues to rise, the call for IOs to act in combating the illicit trafficking of small arms has intensified. The UN, having both the organizational and political capacity to implement and standardize IFM technology along with stockpile destruction programs, must fulfill its duty as an international peacekeeping organization in doing so. Despite the anticipated resistance to this reform, particularly among states whose governments are directly involved in the illicit trade of small arms, they can still be implemented successfully due to the already expressed support of many powerful nations, specifically the United States (Green, 2006). Although the need for the UN to enact and reinforce these reforms is long overdue, the urgency remains, as every day of inaction is equivalent to another 500 lives lost (Amnesty International, 2021). 

### Bibliography

‌Amnesty international. 2012. \"Amnesty International.\" Amnesty.org. 2012. <https://www.amnesty.org/en/what-we-do/arms-control/gun-violence/>.

\"Do Guns Make Us Safer? Science Suggests No.\" 2018. News. July 16, 2018. <https://www.hsph.harvard.edu/news/hsph-in-the-news/do-guns-make-us-safer-science-suggests-no/>.

Green, Eric. \"U.S. Gives \$50,000 for Central America Small Arms Destruction: Focus Is to Stop Illicit Trafficking of Automatic Weapons, Ammunition,\" August 25, 2006. https://www.proquest.com/docview/189978521?accountid=11243&pq-origsite=primo. 

Greene, Owen. \"Examining International Responses to Illicit Arms Trafficking.\" Under the Counter and over the Border, 2000, 151--90. <https://doi.org/10.1007/978-94-015-9335-9_6>.

May, Clifford. \"How Much Is the U.N. Worth?\" FDD. Foundation for Defense of Democracies, October 24, 2017. https://www.fdd.org/analysis/2017/02/01/how-much-is-the-u-n-worth/.  

Kurlantzick, Joshua. 2006. \"Global Gun Rights?\" The New York Times, September 17, 2006, sec. Magazine. https://www.nytimes.com/2006/09/17/magazine/17wwln_essay.html.

\"National Crime Victimization Survey (NCVS).\" 2009. Bureau of Justice Statistics. 2009. <https://bjs.ojp.gov/data-collection/ncvs>.

Lizotte, Todd E., and Orest P. Ohar. \"Tracking Illicit Small Arms Trafficking: Implementation of Intentional Firearm Microstamping (IFM) to Small Arms and Light Weapons Imports and Exports.\" Technologies for Optical Countermeasures VI, 2009. https://doi.org/10.1117/12.830133. 

Noyes, Dan. 2014. \"Frontline: Hot Guns: \'How Criminals Get Guns\' \| PBS.\" Pbs.org. 2014. <https://www.pbs.org/wgbh/pages/frontline/shows/guns/procon/guns.html>.

Peters, Rebecca. \"Small Arms: No Single Solution.\" United Nations. United Nations & the International Action Network on Small Arms. Accessed November 25, 2021. https://www.un.org/en/chronicle/article/small-arms-no-single-solution. 

Security Council. \"Rapid Spread of Small Arms, Light Weapons Still Threatening World Peace, Exacerbating Plight of Civilians in Conflict Zones, Disarmament Chief Tells Security Council \| Meetings Coverage and Press Releases.\" United Nations. United Nations, October 6, 2021. https://www.un.org/press/en/2021/sc14656.doc.htm. 

United Nations Committee on Contributions. \"Committee , Members, Budgetary, Administrative, Contribution, General Assembly.\" United Nations. United Nations, November 12, 2021. https://www.un.org/en/ga/contributions/honourroll.shtml. 

United Nations. \"Global Study on Firearms 2020.\" United Nations : Office on Drugs and Crime, 2020. https://www.unodc.org/unodc/en/firearms-protocol/firearms-study.html. 

United Nations. \"Small Arms and Light Weapons -- UNODA.\" United Nations. Accessed November 1, 2021. <https://www.un.org/disarmament/convarms/salw/>.

UNODA. \"Programme of Action / ITI & the 2030 Agenda for Sustainable Development Implementation, International Cooperation, Assistance,\" 2018. https://www.un.org/disarmament/wp-content/uploads/2018/03/UNODA_PrepCom-2018_2030-Agenda.pdf. 

United Nations Security Council. \"Spread of 1 Billion Small Arms, Light Weapons Remains Major Threat Worldwide, High Representative for Disarmament Affairs Tells Security Council \| Meetings Coverage and Press Releases.\" United Nations. United Nations, February 5, 2020. https://www.un.org/press/en/2020/sc14098.doc.htm. 

Williams, Phil. \"Illicit Markets, Weak States and Violence: Iraq and Mexico.\" Crime, Law and Social Change 52, no. 3 (2009): 323--36. https://doi.org/10.1007/s10611-009-9194-0. 
