---
title: "News Writing Sample"
format: html
editor: visual
---

## Friends General Conference Confronts Institutional Racism

### With the upcoming progress report expected in November, Quakers and committee members reflect on FGC\'s journey toward becoming an anti-racist organization.

#### By: Madison Paulus

#### March 31, 2023

On Tuesday the Institutional Assessment Implementation Committee (IAIC) confirmed that it will be presenting a progress report on the Friends General Conference's (FGC) anti-racism journey during the 2023 Central Committee meeting. 

FGC is the central organization representing the Religious Society of Friends, often referred to as Quakers. Referring to recent anti-racist work within the community, IAIC member Euclid Bautista said, \"confronting racism within Quakerism is necessary because we are dying in terms of numbers in North America, and yet we still have a compelling message to spread.\"

### What are the Institutional Assessment and the IAIC?

The IAIC was created in response to an assessment conducted by Crossroads Ministry in 2016 following reports of Quakers of color being harassed by campus police during FGC gatherings. The assessment identified FGC as a \"club\" institution. FGC reinforces white power and privilege and is only on step two of the six needed to achieve an anti-racist status.

The assessment also identified measures FGC can take in order to become an anti-racist organization. According to Bautista, recommendations include \"addressing the needs of Quakers of color, and helping white Quakers examine how the behaviors and practices contribute to a mostly white and elderly Quaker population.\"

For some members of the IAIC and FGC alike, whether the organization fulfills its goal of becoming an anti-racist organization will determine their involvement in Quakerism in the future. \"As my partners and I are not white, my continued involvement in Quakerism will be based on whether it feels safe to have my children grow up in Quaker spaces,\" said IAIC member Eppchez Yes.

### What can be expected from the progress report?

There is progress to be reported since the institutional assessment in 2016. Yes acknowledged that they have heard more Quakers talk about anti-racism and more programs have been created for Quakers of color. As a Quaker unaffiliated with the IAIC, Jaya Karsemeyer offers an outside perspective on the progress. \"More folks are at ease in discussing racist incidents, which means more visibility of these incidents and less resistance to the idea that this is worthwhile and necessary work,\" said Karsemeyer.

The necessary next steps will undoubtedly be included in the progress report as well. These include \"collecting more demographic data and holding white Quakers accountable for racist actions and biased decision-making,\" according to Bautista.

### Why does anti-racist work matter beyond the Quaker community?

Yes emphasized, \"everyone, Quaker or not, should care about this work because there\'s no liberated future that is not actively anti-racist.\" Karsemeyer added that predominantly white communities cannot thrive without working against racism. \"We\'re lying to ourselves, and absorbed in a shallow existence upholding white supremacy,\" said Karsemeyer.

If you wish to embark on or continue your anti-racist journey, Yes highlighted that the most important parts are listening and self-reflection. Yes continued on to say \"you also have to get comfortable with the fact that we\'re never done with this work and that\'s ok. The point is not to be the best at it, do a good job, and then finish. The point is that this work is ongoing and we can never give up\".
